//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonBanHang
    {
        public int ID_HoaDonBanHang { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Gia { get; set; }
        public string diachi { get; set; }
    }
}
