//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int ID_SanPham { get; set; }
        public string TenSanPham { get; set; }
        public int SoLuong { get; set; }
        public int GiaBan { get; set; }
        public string MoTaSanPham { get; set; }
        public string HinhSanPham { get; set; }
    }
}
